<a href="https://colab.research.google.com/github/chinnusai25/cvit-Workshop2020/blob/master/Day5(May30).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**MORNING SESSION**<br>
Probability and Statistics<br>
https://colab.research.google.com/drive/1CgfWbmRLSkrAYjlQIprpvhALEWrufuVa#scrollTo=w9r5hSUXRCz-

**Sample Vs Population**<br>
Why n-1 in sample variance<br>
**HOG**<br>
gradient = difference between intensities in x and (x+1) or (x-1) cells(in X direction) and y and (y+1) or (y-1) cells(in Y direction)

#### Cancer Test Example
Let us apply Bayes' Rule to a Cancer Test Example which is a very common example in Statistic classes.
Suppose, there is a certain type of cancer which is extremely rare.

Let,
\begin{equation}
P(C) = 0.001
\end{equation}
In other words, $1$ in every $1000$ people has this cancer. Can you compute the probability of not having cancer?
\begin{equation}
P(\neg C) = ?
\end{equation}

The test for cancer is not $100\%$ accurate. Let us say, probability of the test being positive given someone has cancer is,
\begin{equation}
P(pos | C) = 0.8
\end{equation}
Can you compute the probability that the test is negative given someone has cancer?
\begin{equation}
P(neg | C) = ?
\end{equation}

Similarly, the probability of a test being positive given that someone has no cancer is $P(pos | \neg C) = 0.1$. Can you compute the probability that the test is negative given someone has no cancer?
\begin{equation}
P(neg | \neg C) = ?
\end{equation}

Can you compute the following?
\begin{equation}
P(C | pos) = ?
\end{equation}
Interpret the quantity you computed in words!

What we computed is very interesting. We computed probability of having cancer given the test results and how likely the disease is.

In [0]:
P(~C) = 1-P(C) = 1 - 0.001 = 0.999
P(neg|C) = 1-P(pos|C) = 0.2
P(neg|~C) = 0.9
P(C|pos) = P(pos|C)*P(C)|P(pos) = 0.8*0.001|P(pos|C)*P(c)+P(pos|~C)*P(~C) = 0.8*0.001|0.8*(0.001)+0.1*(0.999)

**Robot Localization**

In this exercise we will apply basic concepts of probability and statistics to help a robot localise itself. Robot localization is an important task for any mobile robot as it needs to know where in the world it is currently situated in.

You may think robot localization is a very easy problem as you can use GPS. But no! GPS has errors in localization upto a few metres which is very inaccurate for self driving cars.

Hence, the robot needs to use sensors to locate itself. And sensors are noisy! Even the motion of a robot is uncertain.



In [0]:
# Modify the empty list, p, so that it becomes a UNIFORM probability
# distribution over n grid cells, as expressed in a list of 
# n probabilities.
def init_distribution(n):
    p = [ 1/n for i in range(n) ]
    # Add your code here
    
    # End your code here
    return p

In [19]:
init_distribution(5)

[0.2, 0.2, 0.2, 0.2, 0.2]

In [0]:
#Modify the code below so that the function sense, which 
#takes p and Z as inputs, will output the normalized 
#probability distribution, q, after multiplying the entries 
# in p according to the color in the corresponding cell in world,
# followed by normalization of the probability values

#q should output(P(x/observedColor) which is equal to P(observedColor/x)*P(x)/P(observedColor))
import numpy as np
world=['green', 'red', 'red', 'green', 'green']
p = [0.2, 0.2, 0.2, 0.2, 0.2]

probabilityForCrctObs=0.75
probabilityForInCrctObs=0.25
def sense(p, observedColor):
    q = np.zeros(5)
    # print(q)
    for i in range(5):
      if(observedColor==world[i]):
        q[i]=p[i]*probabilityForCrctObs
      else:
        q[i]=p[i]*probabilityForInCrctObs    
    # End your code here
    return q/np.sum(q)

In [21]:
sense(p, 'red')


array([0.11111111, 0.33333333, 0.33333333, 0.11111111, 0.11111111])

In [22]:
sense(p, 'green')

array([0.27272727, 0.09090909, 0.09090909, 0.27272727, 0.27272727])

In [23]:
#Modify the code so that it updates the probability twice
#and gives the posterior distribution after both 
#measurements are incorporated. Make sure that your code 
#allows for any sequence of measurement of any length.

# DO NOT MODIFY THE SENSE FUNCTION. JUST CALL THE SENSE FUNCTION APPROPRIATELY

p=[0.2, 0.2, 0.2, 0.2, 0.2]
world=['green', 'red', 'red', 'green', 'green']
measurements = ['red', 'green']

# Add your code here
for i in measurements:
  p=sense(p,i)
# End your code here
print(p)

[0.2 0.2 0.2 0.2 0.2]


In [24]:
#Program a function that returns a new distribution 
#q, shifted to the right by U units. If U=0, q should 
#be the same as p.

def gcd(a, b): 
    if b == 0: 
        return a; 
    else: 
        return gcd(b, a%b) 
def move(p, U):
    q = []
    n=len(p)
    d=(n-U)%n
    for i in range(gcd(d,n)): 
          
        # move i-th values of blocks  
        temp = p[i] 
        j = i 
        while 1: 
            k = j + d 
            if k >= n: 
                k = k - n 
            if k == i: 
                break
            p[j] = p[k] 
            j = k 
        p[j] = temp 
    return p 

move([0.11, 0.33, 0.33, 0.11, 0.11], 1)

[0.11, 0.11, 0.33, 0.33, 0.11]

In [25]:
#Modify the move function to accommodate the added 
#probabilities of overshooting or undershooting 
#the intended destination.
def ProbabilisticMove(p, U):
    q = []
    for i in range(5):
        q.append(0.0)
    # ADD CODE HERE
    for i in range(5):
        q[i] = 0.8*p[(i-U)%5] + 0.1*p[(i-U-1)%5] + 0.1*p[(i+1-U)%5]
    # END CODE HERE
    return q
ProbabilisticMove([0, 1.0, 0, 0, 0], 1)

[0.0, 0.1, 0.8, 0.1, 0.0]

In [26]:
# Write code that makes the robot move twice and then prints 
# out the resulting distribution, starting with the initial 
# distribution p = [0, 1, 0, 0, 0]
p=ProbabilisticMove([0, 1.0, 0, 0, 0], 1)
ProbabilisticMove(p, 1)

[0.010000000000000002,
 0.010000000000000002,
 0.16000000000000003,
 0.6600000000000001,
 0.16000000000000003]

In [27]:
#write code that moves 1000 times and then prints the 
#resulting probability distribution.
p = [0, 1, 0, 0, 0]
for i in range(1000):
  p=ProbabilisticMove(p, 1)
print(p)

[0.20000000000000365, 0.20000000000000373, 0.20000000000000365, 0.2000000000000035, 0.2000000000000035]


In [28]:
#Given the list motions=[1,1] which means the robot 
#moves right and then right again, compute the posterior 
#distribution if the robot first senses red, then moves 
#right one, then senses green, then moves right again, 
#starting with a uniform prior distribution.
world=['green', 'red', 'red', 'green', 'green']
measurements = ['red', 'green']
motions = [1,1]

p = [0.2,0.2,0.2,0.2,0.2]
# ADD CODE HERE
for i in range(2):
    q = sense(p, measurements[i])
    # print(q)
    q1 = ProbabilisticMove(q, motions[i])
    # print(q1)
    p = q1
print(p)

[0.21157894736842106, 0.15157894736842106, 0.08105263157894738, 0.16842105263157894, 0.38736842105263164]


**AfterNoon Session**<br>
**Pytorch** <br>
https://colab.research.google.com/drive/1Q5J0HvqFzMWLNlrfNpoVK_vpl8LGVREK#scrollTo=D_oo-7CGNfF5